### ISSUE TITLE
error after recapcha

### ISSUE THREAD

**Issue by sparador** [BjGogosing/discord-acc-creator#5]
[ERROR] Occured while generating account : TimeoutError: Waiting for element to be located By(xpath, //div[text()='"Discord" <noreply@discordapp.com>'])

**Comment by abouchard1** [comment]
Hello sir,

I get the same error:

[ERROR] Occured while generating account : TimeoutError: Waiting for element to be located By(xpath, //div[text()='"Discord" <noreply@discordapp.com>'])
Wait timed out after 30109ms

Did u solved it ?

**Comment by abouchard1** [comment]
@sparador
